# Netlify.toml
[build]
  command = "npm run build"
  publish = "public"

[dev]
  port = 1234
  framework = "#static"
  publish = "public"
  autoLaunch = true
  dir = "public"

[[redirects]]
  from = "/"
  to = "/pages/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/*"
  to = "/pages/post.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/pages/:splat"
  status = 200
  force = false

