# Netlify.toml
[build]
  command = "npm run build"
  publish = "public"

[dev]
  port = 80
  framework = "#static"
  publish = "public"
  autoLaunch = true
  dir = "public"

[[redirects]]
  from = "/"
  to = "/pages/index.html"
  status = 200
  force = true
