import {Entity, PrimaryColumn, ManyToOne} from "typeorm";
import User from "./User.entity";
import Folder from "./Folder.entity";
import FSElement from "./FSElement.abstract.entity";

@Entity()
export class File extends FSElement{
    // Auto generated by combining 'name' with random characters.
    @PrimaryColumn({length: 100})
    loc:string;

    @ManyToOne(()=> Folder, folder=>folder.files)
    folder: Folder;

    @ManyToOne(() => User)
    creator: Partial<User>;
}

export default File;